### ISSUE TITLE
What algorithm for finding Intersection 

### ISSUE THREAD

**Issue by hariharan382** [FlorisSteenkamp/FloBezier#19]
Are you using clipping algorithm to find intersection between two bezier curves, 
And in curve circle intersection, what happens if curves has curvature of some circle of radius R, wouldn't it have infinite intersection, how are you dealing with such cases

**Comment by FlorisSteenkamp** [comment]
I am using implicitization to find intersections. All clipping algorithms have the huge drawback that they can have sublinear or even logarithmic runtimes for hard cases.

Yes, the biggest problem with any intersection algorithm is exactly what you probably found out the hard way, where the radius at the point of intersection of the two curves are almost the same. In these cases, even 'cubically convergent' clipping algorithms go sublinear or logarithmic in their runtimes and can, even in practical cases run for years just to find a single intersection. Implicitization does not have that drawback at all.

Your question about the infinite intersections is correct (or nearly so)! As explained above, this is exactly the problem that no clipping algorithm can solve. It will become slow AND inaccurate in such hard cases. The intersections WON'T become infinite but will have an extremely high condition number (see Wikipedia for info on condition numbers). It won't become infinite because cubic bezier curves cannot represent any part of a circular arc with infinite precision.
