### ISSUE TITLE
Normal computation on degenerate bezier

### ISSUE THREAD

**Issue by aukeroorda** [FlorisSteenkamp/FloBezier#25]
Hi, 

I'm computing the normal of a degenerate bezier curve, one in which the control points lie exactly on the end points. On these curves, the normal is not correctly computed at the endpoints `t=0` and `t=1`.

The bezier is effectively a line, but the `t` values won't line up if it was represented as a line. The bezier is something like:
```js
  const bezier = [[0, 0], [0, 0], [15, 0], [15, 0]];
```
This then results in the normal being `[-0, 0]` at the endpoints, which then gives some difficulties later on.

However, the normal of this bezier is equal to the normal of a line `[[0, 0], [15, 0]]`. If we give this as input to `FloBezier.normal` the output will be `[0, -1]`, also at the end points `t=0` and `t=1`.

So far I've only seen this happen with lines where the control points lie exactly on the endpoints, not when they are somewhere else on the line between the endpoints. This also happens on cubic beziers, when the control point lies on either of the endpoints.

I've locally solved this using the following 'preprocessing' step on beziers before they are input into the `FloBezier.normal` function:
```js
function normalized_bezier(bezier) {
  // This messes up the t-values though, so only use this for normal computation of straight segments.
  // This prevents the computed normal being [-0, 0] at the endpoints t=0 and t=1.
  if (bezier.length == 4) {
    const [[x0, y0], [x1, y1], [x2, y2], [x3, y3]] = bezier;
    if (x0 == x1 && y0 == y1 && x2 == x3 && y2 == y3) {
      // Control points are on the endpoints, this is a line
      return [[x0, y0], [x3, y3]];
    }
  }

  if (bezier.length == 3) {
    const [[x0, y0], [x1, y1], [x2, y2]] = bezier;
    // Control point on first endpoint
    if (x0 == x1 && y0 == y1) {
      return [[x0, y0], [x2, y2]];
    }
    // Control point on second endpoint
    if (x1 == x2 && y1 == y2) {
      return [[x0, y0], [x2, y2]];
    }
  }

  // Nothing to do, return original bezier
  return bezier;
}
```

### Not yet solved
Just now looked into cubic beziers of which just _one_ of the control points lies on the endpoint. Here, it is also unable to compute the normal, but I'm unsure how to fix this case, as these curves can (to my understanding) in general not be reduced in order, and even so, this would then possibly shift the t-values.

**Comment by FlorisSteenkamp** [comment]
Hi.

I'm busy with an explanation of all this and a complete solution but I have other appointments currently so will have to get back to you tomorrow.

**Comment by FlorisSteenkamp** [comment]
```typescript
import { toUnitVector, fromTo as fromToVector } from 'flo-vector2d';
import { generateCuspAtHalf3 } from '../../create/generate-cusp-at-half-t.js';
import { isCubicReallyQuad } from '../../global-properties/classification/is-cubic-really-quad.js';
import { cubicToQuadratic } from '../../transformation/degree-or-type/cubic-to-quadratic.js';
import { fromTo } from '../../transformation/split/from-to.js';
import { classify } from '../../global-properties/classification/classify.js';
```

Reducing the order of a cubic won't change the `t` values at all. However, only in very special cases can this be done without changing the curve, e.g. when
```typescript
const ps = [[0,0],[1,1],[2,1],[3,0]];
isCubicReallyQuad(ps);  //=> true
cubicToQuadratic(ps);  //=> [[0,0],[1.5,1.5],[3,0]]
```

and you are right there cannot be a quadratic order curve for cubic curves having any two points coincident.

Bar floating point round-off the function `normal` always gives the mathematically correct results.

Let's look at cubic curves.

You are correct that when the middle two control points are equal there's nothing special about the curve and it is *not* degenerate.

However, there is one specific special case where the curve is degenerate for t != 0 or 1. It occurs exactly where the curve forms a cusp. It is not easy to find these curves (due to floating point roundoff). They are not  smooth at the cusp and can thus not have a well-defined normal there.

see e.g. [this](https://florissteenkamp.github.io/FloBezier/docs/modules/create_generate_cusp_at_half_t)

An example of such curve with a cusp at t = 0.5 is:
```typescript
const ps = generateCuspAtHalf3([1, 1], [9.59375, 4.59375], [18, 0.5]);
//=> [[1, 1], [18.125, 5.625], [1.125, 6.125], [18, 0.5]]
classify(ps);  //=> { order: 3, realOrder: 3, collinear: false, nodeType: 'cusp' }
normal(ps,0.5);  //=> [0,0]
```

Cusps can also occur at one endpoint and this occurs exactly when either the first two or last two control points are equal, e.g.
```typescript
const psS = [[0,0], [0,0], [15,1], [15,2]];
normal(psS,0);  //=> [0,0]
const psE = [[15,1], [15,2], [0,0], [0,0]];
normal(psE,1);  //=> [0,0]
```

An even more degenerate case occurs when both first and both last endpoints are the same, e.g.
```
const ps = [[0,0], [0,0], [15,0], [15,0]];
normal(ps, 0);  //=> [0,0]
normal(ps, 1);  //=> [0,0]
```

In this case there are two cusps at the endpoints and the curve actually folds in on itself and start going the opposite direction at these extreme points.

To take the example of the cusp at `t = 0.5` again it becomes clear why it is impossible to have a normal at `t = 0.5`
```typescript
const ps = generateCuspAtHalf3([1, 1], [9.59375, 4.59375], [18, 0.5]);

toUnitVector((normal(ps,0.49999999999999)));  //=> [-0.9997328078506795, 0.023115209430073516]
toUnitVector((normal(ps,0.50000000000001)));  //=> [ 0.9997328078506795, -0.023115209430073516]
```

As can be seen the unit normal at an infintesimal value smaller than `t = 0.5` gives a normal roughly equal to `[-0.9997,0.02]` whereas at an infinitesimal value larger than 0.5 the normal is 180 degrees opposite at roughly `[+0.9997,-0.02]`.
At t = 0.5 it is strictly speaking undefined (left and right differentiation is discontinous)

The exact same situation occurs when the first and/or last two endpoints are equal except you don't see the cusp unless you extend the curve beyond the usual `[0,1]` range.

The only cases this can happen is at a cusp and the result will always be `[0,0]` (since the zero vector is normal to all vectors). This knowledge helps a lot since now we only have to check for that specific case and we don't need to mess up our `t` values.

What we thus really need is the normal at t⁺, an infintesimal value larger then `t` because this makes visual sense in some sense.

The other degenerate cases are e.g.
```typescript
const ps = [[3,1], [3,1], [3,1], [4,2]];
normal(ps, 0);  //=> [0,0]
```
and
```typescript
	const ps = [[3,1], [3,1], [3,1], [3,1]];
	normal(ps, 0);  //=> [0,0]
```

So finally the normals at t⁺ can be found by looking at the following control point, e.g.
```typescript
const ps = generateCuspAtHalf3([1, 1], [9.59375, 4.59375], [18, 0.5]);
//=> [[1, 1], [18.125, 5.625], [1.125, 6.125], [18, 0.5]]
  
const ps_ = fromTo(ps,0.5,1);
classify(ps_);  //=> { order: 3, realOrder: 3, collinear: false, nodeType: 'cusp' }
toUnitVector(normal(ps_,-0.0001));  //=> [-0.9996945466108609, +0.024714640934174203]
toUnitVector(normal(ps_,+0.0001));  //=> [+0.9997107246243557, -0.024051342395914787]
const v = fromToVector(ps_[0],ps_[2]);
toUnitVector([-v[1],v[0]]);  //=> [0.9997026906430501, -0.024382992454708537]
```

So, to create a bulletproof 'intuitive normal' for cubic and quadratic curves: (lines have the only degeneracy when both points are coincident)

```typescript
function normal2(ps: number[][], t: number) {
    const n = normal(ps,t);

    if (ps.length < 3 || n[0] !== 0 || n[1] !== 0) {
        return n;  // not degenerate
    }

    if (ps.length === 4) {
        const [[x0,y0], [x1,y1], [x2,y2], [x3,y3]] = ps;
        if (x0 === x1 && y0 === y1) {
            const v = x1 !== x2 || y1 !== y2
                ? fromToVector(ps[0],ps[2])   // only point 0 and 1 coincide
                : fromToVector(ps[0],ps[3]);  // point 0,1 and 2 (and possibly 3) coincide

            return [-v[1],v[0]];  // tangent === [v[0],v[1]]
        }
        
        if (x3 === x2 && y3 === y2) {
            const v = x2 !== x1 || y2 !== y1
                ? fromToVector(ps[1],ps[3])   // only point 3 and 2 coincide
                : fromToVector(ps[0],ps[3]);  // point 3,2 and 1 (and possibly 0) coincide

            return [-v[1],v[0]];  // tangent === [v[0],v[1]]
        }

        // Interior cusp

        // Split curve at cusp
        const ps_ = fromTo(ps,t,1);
        const v = fromToVector(ps_[0],ps_[2]);
        
        return [-v[1],v[0]];  // tangent === [v[0],v[1]]
    }

    if (ps.length === 3) {
        const v = fromToVector(ps[0],ps[2]);

        // points 0 and 1 OR 1 and 2 OR 0,1 and 2 coincide
        return [-v[1],v[0]];  // tangent === [v[0],v[1]]
    }

    return [0,0];  // all points coincident - no normal possible
}
```

**Tests:**
```typescript
// All possible degenerate curves - cubic
const cuspAtInterior = [[1, 1], [18.125, 5.625], [1.125, 6.125], [18, 0.5]];
const cuspAtStart = [[1,1], [1,1], [15,2], [15,-5]];
const cuspAtEnd = [[15,2], [15,-5], [1,1], [1,1]];
const cuspAtStartExtreme = [[1,1], [1,1], [1,1], [15,-5]];
const cuspAtEndExtreme = [[15,2], [1,1], [1,1], [1,1]];
const selfOverlapping = [[1,1], [1,1], [15,2], [15,2]];
const allCoincidentC = [[1,1], [1,1], [1,1], [1,1]];

toUnitVector(normal2(cuspAtInterior, 0.5000001));     //=> [0.9997027067937507, -0.024382330266971487]
toUnitVector(normal2(cuspAtInterior, 0.5));           //=> [0.9997026906430501, -0.024382992454708537]

toUnitVector(normal2(cuspAtStart, 0.000001));         //=> [-0.07124680188879051, 0.9974587175520696]
toUnitVector(normal2(cuspAtStart, 0));                //=> [-0.07124704998790965, 0.9974586998307351]

toUnitVector(normal2(cuspAtEnd, 0.99999));            //=> [-0.3939173572592245, -0.9191458620098926]
toUnitVector(normal2(cuspAtEnd, 1));                  //=> [ -0.39391929857916763, -0.9191450300180578]

toUnitVector(normal2(cuspAtStartExtreme, 0.000001));  //=> [0.39391929857916774, 0.919145030018058]
toUnitVector(normal2(cuspAtStartExtreme, 0));         //=> [0.39391929857916763, 0.9191450300180578]

toUnitVector(normal2(cuspAtEndExtreme, 0.99999));     //=> [0.07124710994878694, -0.9974586955478133]
toUnitVector(normal2(cuspAtEndExtreme, 1));           //=> [0.07124704998790965, -0.9974586998307351]

toUnitVector(normal2(selfOverlapping, 0));            //=> [-0.07124704998790965, 0.9974586998307351]
toUnitVector(normal2(selfOverlapping, 0.5));          //=> [-0.07124704998790965, 0.997458699830735]
toUnitVector(normal2(selfOverlapping, 1));            //=> [-0.07124704998790965, 0.9974586998307351]

normal2(allCoincidentC, 0);  //=> [-0, 0]

// All possible degenerate curves - quadratic
const selfOverlappingStart = [[1,1], [1,1], [2,3]];
const selfOverlappingEnd   = [[1,1], [2,3], [2,3]];
const allCoincidentQ = [[1,1], [1,1], [1,1]];
toUnitVector(normal2(selfOverlappingStart, 0.000001));  //=> [-0.8944271909999159, 0.4472135954999579]
toUnitVector(normal2(selfOverlappingStart, 0));         //=> [-0.8944271909999159, 0.4472135954999579]
toUnitVector(normal2(selfOverlappingEnd, 0.99999));     //=> [-0.894427190999916, 0.447213595499958]
toUnitVector(normal2(selfOverlappingEnd, 1));           //=> [-0.8944271909999159, 0.4472135954999579]
normal2(allCoincidentQ, 0.5);  //?

// All possible degenerate curves - line
const allCoincidentL = [[1,1], [1,1]];
normal2(allCoincidentL, 0.5);  //=> [-0,0]
```


Would you be interested in a pull request by adding an additional function with maybe a better name than `normal2` and maybe even adding the tests? Since `normal` is *technically* correct I don't think it should be changed.

One has to be careful at degenerate or near-degenerate points when it comes to polynomial parametric equations like bezier curves, e.g. check [this](https://math.stackexchange.com/questions/209712/an-almost-straight-curve-with-infinite-curvature) out:

**Comment by FlorisSteenkamp** [comment]
> I see that the result here is correct, but I don't quite understand yet why. I would expect the const v to be defined using the first and second points of the bezier, not the third?

Yes, you're 100% correct and it is true for all non-degenerate cases. But of course the 1st and 2nd points are coincident in those degenerate cases so cannot be used. It just so happens (left as an exercise 🤪) that the the tangent can then be found by using the next control point.

> I think this should not allow for the case where 0, 1 and 2 coincide, although it yields the correct result.

I agree. It would be easier to read the code that way.

> However, it is a somewhat parallel case to Javascripts atan/atan2

This is a great point and pretty funny 😂. Seems they also didn't have a nice short name for the second version and the name stuck. I used to code `atan2` myself since I didn't know it existed as part of JS. It was an ugly mess.

Thanks for taking on the pull request! No rush.
